TARGET = framelesswidget
TEMPLATE = app
QT += widgets
CONFIG += c++17 strict_c++ utf8_source warn_on
DEFINES += WIN32_LEAN_AND_MEAN QT_NO_CAST_FROM_ASCII QT_NO_CAST_TO_ASCII
CONFIG += windeployqt
CONFIG -= embed_manifest_exe
RC_FILE = resources.rc
LIBS += -luser32 -lgdi32 -luxtheme -ldwmapi
HEADERS += qwinwidget.h
SOURCES += qwinwidget.cpp main.cpp
OTHER_FILES += manifest.xml
